version: '3'

services:
  app:
    container_name: app
    build:
      context: ./app
    depends_on:
      - sqlserver
    volumes:
      - ../:/var/www/html

  sqlserver:
    container_name: sqlserver
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: ${SQLSERVER_USER}
      MYSQL_PASSWORD: ${SQLSERVER_PASSWORD}
      MYSQL_DATABASE: ${SQLSERVER_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ../.prepare/templates/sqlserver/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    container_name: webserver
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public

volumes:
###> doctrine/doctrine-bundle ###
  db:
###< doctrine/doctrine-bundle ###